document.addEventListener("DOMContentLoaded",async()=>{if(!getToken())return location.href="/login.html";const u=getUser();if(!["admin","receptionist"].includes(u?.role))return location.href="/dashboard.html";if(u.role!=="admin")document.querySelector("#usersTabNav")?.remove();bindForms();setDefaults();await refreshAll()});
const cache={members:[],plans:[],attendance:[],users:[]};
async function refreshAll(){try{[cache.members,cache.plans,cache.attendance]=await Promise.all([api("/members"),api("/plans"),api("/attendance")]);if(getUser()?.role==="admin")cache.users=await api("/users");render();}catch(e){alert(e.message)}}
function render(){document.querySelector("#memberRows").innerHTML=cache.members.map(m=>`<tr><td>${esc(m.name)}</td><td>${esc(m.phone||"—")}</td><td>${esc(m.email)}</td><td>${esc(m.plan_name||"—")}</td><td>${esc(m.join_date||"—")}</td><td>${esc(m.expiry_date||"—")}</td><td><span class="badge badge-soft">${esc(m.status)}</span></td><td><button class="btn btn-sm btn-outline-danger" onclick="delMember(${m.id})">Delete</button></td></tr>`).join("")||empty(8,"No members.");document.querySelector("#planRows").innerHTML=cache.plans.map(p=>`<tr><td>${esc(p.plan_name)}</td><td>৳${Number(p.price).toLocaleString()}</td><td>${p.duration_days} days</td><td><button class="btn btn-sm btn-outline-danger" onclick="delPlan(${p.id})">Delete</button></td></tr>`).join("")||empty(4,"No plans.");document.querySelector("#attendanceRows").innerHTML=cache.attendance.map(a=>`<tr><td>${esc(a.member_name)}</td><td>${a.member_id}</td><td>${esc(a.date)}</td><td>${esc(a.check_in_time)}</td><td><button class="btn btn-sm btn-outline-danger" onclick="delAttendance(${a.id})">Delete</button></td></tr>`).join("")||empty(5,"No records.");document.querySelector("#userRows").innerHTML=cache.users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td><span class="badge badge-soft">${esc(u.role)}</span></td><td><button class="btn btn-sm btn-outline-danger" onclick="delUser(${u.id})">Delete</button></td></tr>`).join("")||empty(4,"No users.");document.querySelector("#new_plan").innerHTML='<option value="">No plan</option>'+cache.plans.map(p=>`<option value="${p.id}">${esc(p.plan_name)}</option>`).join("");document.querySelector("#attendance_member").innerHTML=cache.members.map(m=>`<option value="${m.id}">${esc(m.name)} (#${m.id})</option>`).join("");document.querySelector("#statMembers").textContent=cache.members.length;document.querySelector("#statPlans").textContent=cache.plans.length;document.querySelector("#statAttendance").textContent=cache.attendance.filter(a=>a.date===new Date().toISOString().slice(0,10)).length;document.querySelector("#statUsers").textContent=cache.users.length}
function bindForms(){document.querySelector("#memberForm").onsubmit=async e=>{e.preventDefault();await post("/members",{name:v("new_name"),email:v("new_email"),phone:v("new_phone"),plan_id:v("new_plan")||null,join_date:v("new_join"),expiry_date:v("new_expiry"),status:v("new_status")},"memberModal",e.target)};document.querySelector("#planForm").onsubmit=async e=>{e.preventDefault();await post("/plans",{plan_name:v("plan_name"),price:v("plan_price"),duration_days:v("plan_days")},"planModal",e.target)};document.querySelector("#attendanceForm").onsubmit=async e=>{e.preventDefault();await post("/attendance",{member_id:v("attendance_member"),date:v("attendance_date"),check_in_time:v("attendance_time")},"attendanceModal",e.target)};document.querySelector("#userForm").onsubmit=async e=>{e.preventDefault();await post("/users",{name:v("user_name"),email:v("user_email"),password:v("user_password"),role:v("user_role")},"userModal",e.target)}}
async function post(path,data,modal,form){try{await api(path,{method:"POST",body:JSON.stringify(data)});bootstrap.Modal.getInstance(document.getElementById(modal))?.hide();form.reset();setDefaults();await refreshAll();}catch(e){alert(e.message)}}
async function delMember(id){if(confirm("Delete this member?")){await api("/members/"+id,{method:"DELETE"});refreshAll()}}async function delPlan(id){if(confirm("Delete this plan?")){try{await api("/plans/"+id,{method:"DELETE"});refreshAll()}catch(e){alert(e.message)}}}async function delAttendance(id){if(confirm("Delete this attendance record?")){await api("/attendance/"+id,{method:"DELETE"});refreshAll()}}async function delUser(id){if(confirm("Delete this user?")){try{await api("/users/"+id,{method:"DELETE"});refreshAll()}catch(e){alert(e.message)}}}
function setDefaults(){let d=new Date().toISOString().slice(0,10);document.querySelector("#new_join").value=d;document.querySelector("#attendance_date").value=d;document.querySelector("#attendance_time").value=new Date().toTimeString().slice(0,5)}
function v(id){return document.getElementById(id).value}function empty(n,t){return`<tr><td colspan="${n}" class="muted py-4">${t}</td></tr>`}function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
